DROP TABLE IF EXISTS `UTILISATEUR`;
DROP TABLE IF EXISTS `ROLE`;
DROP TABLE IF EXISTS `FESTIVAL`;

CREATE TABLE IF NOT EXISTS `ROLE`(
  `ROLE` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ROLE`)
);

CREATE TABLE IF NOT EXISTS `UTILISATEUR`(
  `PSEUDO` VARCHAR(20) NOT NULL,
  `MOT_DE_PASSE` VARCHAR(20) NOT NULL,
  `ROLE` VARCHAR(20) DEFAULT 'UTILISATEUR',
  PRIMARY KEY (`PSEUDO`),
  FOREIGN KEY (`ROLE`) REFERENCES `ROLE`(`ROLE`)
);

CREATE TABLE IF NOT EXISTS `FESTIVAL`(
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOM` VARCHAR(20) NOT NULL,
  `DATE_DEBUT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `DATE_FIN` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
);

INSERT INTO `ROLE`(`ROLE`) VALUES ('UTILISATEUR');
INSERT INTO `ROLE`(`ROLE`) VALUES ('ADMINISTRATEUR');